### ISSUE TITLE
Not running on termux

### ISSUE THREAD

**Issue by luisadha** [kawaii-ghost/deshc#1]
./deshc.sh: 4: playx102-bin: not found
./deshc.sh: 6: kill: No such process

cat: /proc/14416/cmdline: No such file or directory
./deshc.sh: 8: kill: No such process

**Comment by luisadha** [comment]
![Uploading Screenshot_2023-12-25-11-58-47-600_com.termux.jpg…]()

**Comment by luisadha** [comment]
![Screenshot_2023-12-25-11-58-47-600_com termux](https://github.com/kawaii-ghost/deshc/assets/40796508/d3c2b5a3-e319-49f7-87b1-628d8d9cd1df)

**Comment by kawaii-ghost** [comment]
You didn't need to learn entire shell scripting to configure this error.
First it stated that `playx102-bin` not found. Yet the script didn't find such file. 
> I didn't even obfuscate the script so you can observe what it did.

Bonus comment, You didn't know what is termux exactly if you think this script is platform specific.

You can find my writeup down here.
https://medium.com/@kaw411gh0st/membongkar-program-shc-encrypted-shell-script-1d945b76080b

**Comment by luisadha** [comment]
![Screenshot_2023-12-26-08-17-15-269_com termux](https://github.com/kawaii-ghost/deshc/assets/40796508/84f02473-b1d2-48ba-8a89-c994799adcbe)

No errors but empty results

**Comment by kawaii-ghost** [comment]
Try to change the shebang of `deshc.sh` into Termux preferences.

**Comment by kawaii-ghost** [comment]
Android hierarchy problem, ,`#!/system/bin/sh`

**Comment by datfooldive** [comment]
> ./deshc.sh: 4: playx102-bin: not found
> ./deshc.sh: 6: kill: No such process
> 
> cat: /proc/14416/cmdline: No such file or directory
> ./deshc.sh: 8: kill: No such process

try 

`termux-fix-shebang deshc.sh` and run again

`./deshc.sh ./target`

**Comment by luisadha** [comment]
Successfull decrypt drawercli.x howover
Failed decrypt playx because playx kill itself before before being read by decsh

**Comment by kawaii-ghost** [comment]
Just...... adjust..... the sleep time.........

**Comment by kawaii-ghost** [comment]
> You didn't need to learn entire shell scripting to configure this error. First it stated that `playx102-bin` not found. Yet the script didn't find such file.
> 
> > I didn't even obfuscate the script so you can observe what it did.
> 
> Bonus comment, You didn't know what is termux exactly if you think this script is platform specific.
> 
> You can find my writeup down here. https://medium.com/@kaw411gh0st/membongkar-program-shc-encrypted-shell-script-1d945b76080b

Ini udah dibaca belom?

**Comment by luisadha** [comment]
Udah dibaca, udah selesai masalahnya
