### ISSUE TITLE
Isi File $arg.dec.sh kosong

### ISSUE THREAD

**Issue by eraselk** [kawaii-ghost/deshc#2]
Gw mendapati masalah pada device android dengan menggunakan aplikasi termux sebagai terminalnya, yaitu pada saat gw selesai mengeksekusi scriptnya lalu gw check isi file `$arg.dec.sh` kosong. Mohon bantuannya

**Comment by kawaii-ghost** [comment]
Kayaknya ini masih ada hubungannya ama issue sebelumnya, masalah shebang di Linux ama file hierarchy Android beda. Aku update dulu supaya pada pake `sh`

**Comment by eraselk** [comment]
udah bisa sih bang sebenernya

**Comment by eraselk** [comment]
Gua modif dikit [deshc.zip](https://github.com/kawaii-ghost/deshc/files/13790009/deshc.zip)

**Comment by kawaii-ghost** [comment]
Jadi, gimana?

Pada Jum, 29 Des 2023 pukul 06.16 eraselk ***@***.***>
menulis:
